### ISSUE TITLE
Styling Text

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/svg-activity#12]
Would love to be able to style and align text within an SVG. Right now text does not retain characteristics from flash, and it's causing problems with position, and getting cut off.

**Comment by iMcKelvie** [comment]
Additional info: You can check out Step 7 in DCVs module to see where this desperately needed. 

I would be happy to maintain a separate style sheet to be applied to the SVG, if that would be helpful! Or happy to roll it into the regular page stylesheet if that's better for you.

**Comment by ivanreese** [comment]
One possibility: if there's a separate stylesheet specifically for SVGs, SVGActivity can access that sheet through the JS API and then inject it into each SVG.

**Comment by theseanzo** [comment]
Moved to [SVG ACtivity Components](https://github.com/cdig/svg-activity-components/issues/8)
