### ISSUE TITLE
Green Highlight Color Adjustment

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity#15]
Can we tweak the color a bit on the green highlight code to be more like it was in Flash? It washes out the details a bit too much in the new SVG highlight code.

The old Flash highlight didn't work on black, so it took some extra work and invisible symbols... so if we can find a way that addresses both these issues that would be great!

**Comment by theseanzo** [comment]
@crystalrubik, can we look at this tomorrow together?

**Comment by crystalrubik** [comment]
Yuppers!


*Crystal Rubik*
Designer/Animator
CD Industrial Group Inc.
···································
crystal@cdiginc.com
1-866-628-3224
www.cdiginc.com

**Comment by theseanzo** [comment]
Closed and moved to [SVG Activity Components]https://github.com/cdig/svg-activity-components/issues/7)
