### ISSUE TITLE
SVG and Highlight not working properly in IE

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity#16]
The SVG's (newly updated) with the green highlight code don't scale nicely (they are squished vertically) and the highlight code once highlighted stays on in IE 11. 

![svg](https://cloud.githubusercontent.com/assets/8481323/10111251/e7b10e4c-638f-11e5-831a-9eb4aa341810.jpg)

The way it should look...

![svg-in-chrome](https://cloud.githubusercontent.com/assets/8481323/10111271/1adbb722-6390-11e5-8845-97f12a792a70.png)

**Comment by theseanzo** [comment]
The scaling of the SVG is just an HTML issue with how you scale the image, not an actual bug in the activity. You just need to change your css.
