### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by ivanreese** [cdig/svg-activity#19]
Let's say we have a symbol definition like this (some boilerplate lines omitted):

```coffee
    return scope =
      setup: ()->
        scope.joystick.registerCallback(scope.setSpeed)
      setSpeed: (joystickLevel)->
        # Do something with joystickLevel
```

We have a function on the scope (setSpeed). It's on the scope so that we can call it manually from other code. We'd also like to use it as a callback.

Is that cool? Is there any risk of a race condition, where scope.setSpeed might be undefined at the time scope.setup is executed?

-------

I guess... in the general case, I'm asking if it's guaranteed that all of the scope is defined at the time the scope functions start executing. Of course, if you add things to scope from inside a scope function, you're fucked. But if you're just referring to other things declared on the scope at load time.. is that okay?

My hunch is "Yes", but I want to make sure this is a well-considered case.

**Comment by ivanreese** [comment]
I'm closing this because I'm 99.99999% sure that the answer is yes, because I can't fathom an execution order that wouldn't work in this case.

**Comment by theseanzo** [comment]
Since an object is actually created before setup is called, it's impossible for the race condition to happen!

**Comment by ivanreese** [comment]
You would run into trouble if you were creating new scope properties inside a scope function, though. That's what got me wondering. Thanks for the follow-up.
