### ISSUE TITLE
SVG Activity Locking

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/svg-activity#20]
Hi, Sean! Can you please create or point to a quick example of how to cause an interaction in an SVG activity to become a cd-activity? E.G. I have a bobcat with a joystick to adjust the wheel speed. I want to cause the screen to lock there, and award points when the user manipulates the joystick. Can you please point me at an example of how to do this?

**Comment by theseanzo** [comment]
I'll show you tomorrow in Red Deer!

**Comment by ivanreese** [comment]
Warning! Scoring is going to change (a lot) in cd-module v2, and change again, and again, for the next few months. So whatever you end up doing, please make sure I know what it is, so I can do my best to not break your stuff when I change my stuff.
