### ISSUE TITLE
Interactivity on mobile?

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity#4]
When I tried testing my svg activity on mobile I found that iOS commands for click and drag trump what I am trying to tell the animation to do. I think it's because mobile doesn't actually have mouse events to capture. I know there is a way to turn of the default activity so I am requesting a lesson or a tool or something to help with this.

**Comment by ivanreese** [comment]
There are two parts to this. One is to use touch events in addition to mouse events. The other is to use `preventDefault`. Sean knows how to do these things, so just nag him a few times and your wish will come true.

**Comment by theseanzo** [comment]
Should be resolved by Pointer Events
