### ISSUE TITLE
Scrolling?

### ISSUE THREAD

**Issue by ivanreese** [cdig/svg-activity#5]
It seems I can't use 2-finger scrolling on my Mac+Safari if the mouse cursor is on top of an SVG. Not sure if this applies to *all* SVGs, or just those that have been processed by SVGActivity, or those that are embedded with `<object>`, or otherwise.

**Comment by crystalrubik** [comment]
You can't scroll with a mouse over an SVG in Safari either. Seems to work everywhere else though including FF on Mac and Windows 7, IE on Windows 7 and Chrome on Mac and Windows 7.

**Comment by theseanzo** [comment]
This is a property of ```<object>```
