### ISSUE TITLE
Resizing through largest breakpoint kills animation

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity#6]
At about 1025px (the widest breakpoint) the animation breaks. The invisible arrows reappear as if it wasn't animated at all. Test case uploaded to slack.

Browser: Chrome on Mac.

**Comment by ivanreese** [comment]
To be more specific — if you resize the browser window past 1025px (in either direction, larger or smaller), it causes the glitch.

**Comment by theseanzo** [comment]
Moved to [SVG Activity Components](https://github.com/cdig/svg-activity-components/issues/11)
