### ISSUE TITLE
Crank no worky on devices in some views

### ISSUE THREAD

**Issue by crystalrubik** [cdig/svg-activity#8]
Crank works well on the iPad Mini in portrait view and iPhone in landscape view. I can't get it to turn far at all on the iPhone in portrait view or the iPad mini in landscape view. Even if zoomed in. Yup, weird.

iPhone 5S portrait view.
iPad Mini landscape view.

**Comment by theseanzo** [comment]
Moved to [SVG Activity Components](https://github.com/cdig/svg-activity-components/issues/9)
