### ISSUE TITLE
SVG's in cd-rows

### ISSUE THREAD

**Issue by Nathanoid** [cdig/svg-activity#9]
Svg's don't work real well if they are in a cd-row element. In my example, it works fine in row view but when you change to column view the svg doesn't display. Like it doesn't exist at al.

**Comment by ivanreese** [comment]
It probably just has 0 height in column view. This will probably be fixed in cd-module 2 (coming soon-ish)

**Comment by crystalrubik** [comment]
Hurry! :)

I have same issue now too. I guess I can avoid cd-row for now.

**Comment by theseanzo** [comment]
Should be fixed!
